package:
  name: curl
  version: "8.11.0"

source:
  url: https://curl.se/download/curl-8.11.0.tar.gz
  sha256: 264537d90e58d2b09dddc50944baf3c38e7089151c8986715e2aaeaaf2b8118f

build:
  number: '0'
  run_exports:
    - curl >=8.11.0,<8.12.0a0
  script_env:
    - CMAKE_GENERATOR=Ninja

dependencies:
  host:
    - cmake
    - ninja
    - openssl
    - zlib
  run:
    - openssl
    - zlib

about:
  home: https://curl.se/
  license: MIT
  summary: "cURL - command line tool and library for transferring data with URLs"

extra:
  copy_test_source_files: true
  final: true
